// Generated by CoffeeScript 1.7.1
(function() {
  var fs, getBase64, imgType, prefixTmpl,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require('fs');

  imgType = ['jpg', 'gif', 'png'];

  prefixTmpl = 'data:image/{format};base64,';

  getBase64 = function(path) {
    var fileList;
    return fileList = fs.readdir(path, function(err, fileList) {
      var base64Content, ext, file, fileName, filePath, fileStat, name, prefix, txtFileName, _i, _len, _results;
      _results = [];
      for (_i = 0, _len = fileList.length; _i < _len; _i++) {
        fileName = fileList[_i];
        filePath = path + '/' + fileName;
        fileStat = fs.statSync(filePath);
        if (fileStat.isDirectory()) {
          _results.push(getBase64(filePath));
        } else {
          name = fileName.split('.')[0];
          ext = fileName.split('.')[1];
          if (__indexOf.call(imgType, ext) < 0) {
            continue;
          }
          txtFileName = name + '.txt';
          prefix = prefixTmpl.replace('{format}', ext);
          file = fs.readFileSync(filePath);
          base64Content = file.toString('base64');
          _results.push(fs.writeFile(path + '/' + txtFileName, prefix + base64Content));
        }
      }
      return _results;
    });
  };

  getBase64('.');

}).call(this);
